import { takeLatest, all } from "redux-saga/effects";

/* ------------- Types ------------- */
import { AuthTypes } from "../models/auth";
import { MainTypes } from "../models/main";
/* ------------- Sagas ------------- */
import {
  signInByEmail,
  getAccountInfo,
  logOut,
  getBolletiniBianchi,
  getBolletiniPremercati,
  getPayments,
  getRechargeMobile,
  getPostePay,
  getAds,
  createAds,
  getRegister,
  getChangedPassword,
  getConfigura,
  getCodiceTicket,
  getBarcodeData,
  getUserDetail,
  updateUserDetail,
  changeAgent,
  getAgents,
  getSkinExtras,
  getErrors,
  deleteError,
  sendDataForm,
  getDataFormDetails,
  getTicketByTicketId,
  updateDataForm,
  sendVisureDetails,
  addPrivateMsg,
  addTicket,
  getVisure,
  getDataFormDetailsActives,
  getVisureByVisureId,
  addVisure,
  updateVisura,
  getUserByUserId,
  getAgentByUserId,
  getSkins,
  getFaturaDetails,
  getAllServices,
  sendMailFattura,
  getAllFaturaBySearch,
  getPaymentsForExcel,
  AddSkinNew,
  getWidgetPayments,
  AddSuperAdmin,
  AddExtraData,
  getStatistiche,
  UpdateServiceChangeStatus,
  getBgameVoucherReq,
  getStatisticheMain,
  fetchBolletini,
  buyTicketOnline,
  setPagoPa,
  setMavRav,
  payPagoPa,
  setBokingSep,
  setPayFSaga,
} from "./AuthSagas";

import {
  getServices,
  getUsers,
  getUsersSimple,
  getUsersBySearch,
  getOverviewDashboard,
  toggleFavorite,
  getFavorites,
} from "./MainSagas";

export default function* root() {
  yield all([
    // AUTH
    takeLatest(AuthTypes.SET_PAY_F_SAGA, setPayFSaga),
    takeLatest(AuthTypes.SET_BOKING_SEP, setBokingSep),
    takeLatest(AuthTypes.PAY_PAGO_PA, payPagoPa),
    takeLatest(AuthTypes.SET_MAV_RAV, setMavRav),
    takeLatest(AuthTypes.SET_PAGO_PA, setPagoPa),
    takeLatest(AuthTypes.BUY_TICKET_ONLINE, buyTicketOnline),
    takeLatest(AuthTypes.FETCH_BOLLETINI, fetchBolletini),
    takeLatest(AuthTypes.GET_STATISTICHE_MAIN, getStatisticheMain),
    takeLatest(AuthTypes.GET_BGAME_VOUCHER_REQ, getBgameVoucherReq),
    takeLatest(
      AuthTypes.UPDATE_SERVICES_CHANGE_STATUS,
      UpdateServiceChangeStatus
    ),
    takeLatest(AuthTypes.GET_STATISTICHE, getStatistiche),
    takeLatest(AuthTypes.ADD_EXTRA_DATA, AddExtraData),
    takeLatest(AuthTypes.ADD_SUPER_ADMIN, AddSuperAdmin),
    takeLatest(AuthTypes.GET_PAYMENTS_FOR_EXCEL, getPaymentsForExcel),
    takeLatest(AuthTypes.ADD_SKIN_NEW, AddSkinNew),
    takeLatest(AuthTypes.SEND_MAIL_FATTURA, sendMailFattura),
    takeLatest(AuthTypes.GET_ALL_FATURA_BY_SEARCH, getAllFaturaBySearch),
    takeLatest(AuthTypes.GET_ALL_SERVICES, getAllServices),
    takeLatest(AuthTypes.GET_FATURA_DETAILS, getFaturaDetails),
    takeLatest(AuthTypes.GET_WIDGET_PAYMENTS, getWidgetPayments),

    takeLatest(AuthTypes.GET_SKINS, getSkins),
    takeLatest(AuthTypes.UPDATE_VISURA, updateVisura),
    takeLatest(AuthTypes.ADD_VISURE, addVisure),
    // AUTH h
    takeLatest(AuthTypes.GET_AGENT_BY_USER_ID, getAgentByUserId),
    takeLatest(AuthTypes.GET_USER_BY_USER_ID, getUserByUserId),
    takeLatest(AuthTypes.GET_VISURE_BY_VISURE_ID, getVisureByVisureId),
    takeLatest(AuthTypes.GET_VISURE, getVisure),
    takeLatest(
      AuthTypes.GET_DATA_FORM_DETAILS_ACTIVES,
      getDataFormDetailsActives
    ),
    takeLatest(AuthTypes.ADD_TICKET, addTicket),
    takeLatest(AuthTypes.ADD_PRIVATE_MSG, addPrivateMsg),
    takeLatest(AuthTypes.SEND_VISURE_DETAILS, sendVisureDetails),
    takeLatest(AuthTypes.UPDATE_DATA_FORM, updateDataForm),
    takeLatest(AuthTypes.GET_TICKET_BY_TICKET_ID, getTicketByTicketId),
    takeLatest(AuthTypes.GET_DATA_FORM_DETAILS, getDataFormDetails),
    takeLatest(AuthTypes.SEND_DATA_FORM, sendDataForm),
    takeLatest(AuthTypes.SIGN_IN_BY_EMAIL, signInByEmail),
    takeLatest(AuthTypes.GET_ACCOUNT_INFO, getAccountInfo),
    takeLatest(AuthTypes.LOG_OUT, logOut),
    takeLatest(AuthTypes.GET_BOLLETINI_BIANCHI, getBolletiniBianchi),
    takeLatest(AuthTypes.GET_BOLLETINI_PREMERCATI, getBolletiniPremercati),
    takeLatest(AuthTypes.GET_BARCODE_DATA, getBarcodeData),
    takeLatest(AuthTypes.GET_PAYMENTS, getPayments),
    takeLatest(AuthTypes.GET_RECHARGE_MOBILE, getRechargeMobile),
    takeLatest(AuthTypes.GET_POSTE_PAY, getPostePay),
    takeLatest(AuthTypes.GET_ADS, getAds),
    takeLatest(AuthTypes.CREATE_ADS, createAds),
    takeLatest(AuthTypes.GET_REGISTER, getRegister),
    takeLatest(AuthTypes.GET_CHANGED_PASSWORD, getChangedPassword),
    takeLatest(AuthTypes.GET_CONFIGURA, getConfigura),
    takeLatest(AuthTypes.GET_CODICE_TICKET, getCodiceTicket),
    takeLatest(AuthTypes.GET_USER_DETAIL, getUserDetail),
    takeLatest(AuthTypes.UPDATE_USER_DETAIL, updateUserDetail),
    takeLatest(AuthTypes.CHANGE_AGENT, changeAgent),
    takeLatest(AuthTypes.GET_AGENTS, getAgents),
    takeLatest(AuthTypes.GET_SKIN_EXTRAS, getSkinExtras),
    takeLatest(AuthTypes.GET_ERRORS, getErrors),
    takeLatest(AuthTypes.DELETE_ERROR, deleteError),
    // MAIN
    takeLatest(MainTypes.GET_SERVICES, getServices),
    takeLatest(MainTypes.GET_USERS, getUsers),
    takeLatest(MainTypes.GET_USERS_SIMPLE, getUsersSimple),

    takeLatest(MainTypes.GET_USERS_BY_SEARCH, getUsersBySearch),
    takeLatest(MainTypes.GET_OVERVIEW_DASHBOARD, getOverviewDashboard),
    takeLatest(MainTypes.TOGGLE_FAVORITE, toggleFavorite),
    takeLatest(MainTypes.GET_FAVORITES, getFavorites),
  ]);
}
